version: "2"
services:
  inova-responde:
    environment:
    - DB_USER=milito
    - DB_PASS=lautaro
    - DB_URL=159.89.87.78:27017
    - ML_CLIENT_ID=3659532861516182
    - ML_CLIENT_SECRET=EezWxXN7ip0Jd55Gvyp4Vn7xU0phnrxh
    - DB_NAME=mercadolibre
    container_name: inova-responde
    image: inova-responde
    restart: always
    ports:
      - "85:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/responde:/data
    
