version: "2"
services:
  inova-responde:
    environment:
    - ML_CLIENT_ID=5588464117413382
    - ML_CLIENT_SECRET=6bPIOKSqCaHeNyxWb4kRbtP0eM9d1Tkw
    - URL_ACTUAL=https://mlgestion.net
    container_name: inova-responde
    image: inova-responde
    restart: always
    ports:
      - "85:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/responde:/data
    
